name: NDS

on: [push, pull_request]

jobs:
  build:
    name: NDS build
    runs-on: ubuntu-latest
    container: 
      image: skylyrac/blocksds:dev-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install zlib
      run: wf-pacman -Syu toolchain-gcc-arm-none-eabi-zlib

    - name: Make
      run: |
        make clean
        make
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NDS ROM
        path: ./ddnet-nds.nds
